spring:
  application:
    name: eureka-consumer

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int[0,1000]}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1